# Generated by Django 4.2.4 on 2023-08-29 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskresult',
            name='ip_address',
            field=models.GenericIPAddressField(default='0.0.0.0'),
        ),
    ]
