# Generated by Django 4.2.4 on 2023-08-29 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_taskresult_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskresult',
            name='xss_number',
            field=models.IntegerField(default=0),
        ),
    ]
